Repository kol-oss/database-coursework, pull requests merged in 2023-11, with the labels that each got.

#83 Fix the logic of notification managing
  docs/requirements/stakeholders-needs.md
  docs/use cases/README.md
Labels: enhancement

#86 Add business object model
  docs/design/README.md
Labels: documentation, models

#89 Refactor model of business-objects
  docs/design/README.md
Labels: documentation, models

#90 Add the first part of ER-model
  docs/design/README.md
Labels: models

#91 Add the second part of ER-model
  docs/design/README.md
Labels: models

#92 Fix business-objects model and ER-model
  docs/design/README.md
Labels: models

#93 Create SQL-model
  docs/design/README.md
  docs/design/relational_scheme.png
Labels: documentation, models

#94 Fix business-objects model
  docs/design/README.md
Labels: models

#95 Fix ER-model
  docs/design/README.md
Labels: models

#96 Fix notification table
  docs/design/relational_scheme.png
Labels: bug, models

#97 Fix relational scheme
  docs/design/relational_scheme.png
Labels: bug, documentation

#98 Small fixes of relational scheme
  docs/design/relational_scheme.png
Labels: bug, documentation

#103 Add SQL-script layout
  docs/software/README.md
Labels: SQL

#104 Add foreign keys
  docs/software/README.md
Labels: SQL

#105 Add seed script
  docs/software/README.md
Labels: SQL

#106 Add indexes
  docs/software/README.md
Labels: SQL

#107 Add "projects", "roles", "permissions" tables creating
  docs/software/README.md
Labels: SQL

#108 Add tables
  docs/software/README.md
Labels: SQL

#110 Add "users", "messages", "notifications" tables
  docs/software/README.md
Labels: SQL

#112 Fix typo in the title
  docs/software/README.md
Labels: SQL
